/** Closed token set. Components consume names. No one-off hex at call sites. */

export const T = {
  canvas: '#141414',
  sidebar: '#161616',
  raised: '#1F1F1F',
  composer: '#1C1C1C',
  overlay: '#E6EAF214',
  overlayStrong: '#E6EAF224',
  clear: '#00000000',
  border: '#E6EAF218',
  borderStrong: '#E6EAF230',
  sidebarBorder: '#2A2A2A',
  text: '#E8E8E8',
  secondary: '#A8A8A8',
  tertiary: '#7A7A7A',
  ghost: '#5A5A5A',
  accent: '#D4D4D4',
  inverse: '#ECECEC',
  onInverse: '#161616',
  danger: '#C45C5C',
  space: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    control: 6,
    inset: 5,
  },
  size: {
    dot: 8,
    badge: 16,
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    dot: 4,
    badge: 8,
  },
  type: {
    xs: 11,
    sm: 12,
    md: 14,
    lg: 16,
  },
  line: {
    sm: 16,
    md: 20,
    lg: 24,
  },
  motion: {
    sidebarMs: 200,
  },
  layout: {
    sidebarWidth: 252,
    titlebarHeight: 48,
    contentMax: 720,
    trafficLightClearance: 86,
  },
  stroke: {
    none: 0,
    hairline: 1,
  },
} as const

export const CHAT_THEME = {
  text: T.text,
  textMuted: T.secondary,
  textFaint: T.tertiary,
  textDim: T.secondary,
  border: T.border,
  bg: T.canvas,
  accent: T.accent,
  caret: T.accent,
  fontSans: 'Helvetica',
  codeText: T.secondary,
  codeWash: T.overlay,
  metrics: {
    mdTextSize: T.type.md,
    mdLineHeight: T.line.lg,
    mdBlockGap: 14,
    mdHeadingSizes: [20, 16, 14, 14],
    mdHeadingLineHeights: [28, 24, 22, 22],
    codeTextSize: 12.5,
    codeLineHeight: 20,
    codeRadius: T.radius.md,
    codeHeaderTextSize: T.type.sm,
    diffLineHeight: 20,
    diffFileHeaderHeight: 34,
  },
}
